fix rb

diff --git a/.github/workflows/prod-pipeline.yml b/.github/workflows/prod-pipeline.yml
--- a/.github/workflows/prod-pipeline.yml
+++ b/.github/workflows/prod-pipeline.yml
@@ -185,7 +185,12 @@ jobs:
       - name: Set output for integration failed
         id: set-failure-status
         run: |
-          echo "integration_failed=$([[ $? -ne 0 ]] && echo true || echo false)" >> $GITHUB_OUTPUT
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "integration_failed=true" >> $GITHUB_OUTPUT
+          else
+            echo "integration_failed=false" >> $GITHUB_OUTPUT
+          fi
     
       - name: Log integration failed output
         run: |
